yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # main page
    path('', views.index, name='index'),
    # page for a certain group
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # User profile
    path('profile/<str:username>/', views.profile, name='profile'),
    # One post view
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Create a new post
    path('create/', views.post_create, name='post_create'),
    # Edit post page
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # import rules from app posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        null=True,
        blank=True,
        related_name='posts',
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ('group', 'text',)

        labels = {
            'group': ('Группа'),
            'text': ('Текст'),
        }

        help_texts = {
            'group': ('Выберите группу для новой записи'),
            'text': ('Добавьте текст для новой записи'),
        }

yatube/posts/views.py
import os

from django.core.paginator import Paginator

from django.shortcuts import get_object_or_404, render, redirect

from django.contrib.auth.decorators import login_required

from .models import Group, Post, User

# from django.contrib.auth.models import User

from .forms import PostForm


PATH_TO_INDEX = os.path.join('posts', 'index.html')
PATH_TO_GROUP_LIST = os.path.join('posts', 'group_list.html')
PATH_TO_PROFILE = os.path.join('posts', 'profile.html')
PATH_TO_POST = os.path.join('posts', 'post_detail.html')
PATH_TO_CREATE_POST = os.path.join('posts', 'create_post.html')
# POST_LENGTH = 10
POSTS_IN_PAGINATOR = 10


def index(request):
    """Return main page."""
    template = PATH_TO_INDEX
    # title = 'Main page for project Yatube'
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, POSTS_IN_PAGINATOR)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def group_posts(request, slug):
    """View-function for group page."""
    template = PATH_TO_GROUP_LIST
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS_IN_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Code to the model and the creation of the context dict for user."""
    template = PATH_TO_PROFILE
    author = get_object_or_404(User, username=username)
    posts = author.posts.all().order_by("-pub_date")
    paginator = Paginator(posts, POSTS_IN_PAGINATOR)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_count': author.posts.count(),
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Code to the model and the creation of the context dict for posts."""
    template = PATH_TO_POST
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    posts_count = author.posts.count()
    context = {
        'post': post,
        'posts_count': posts_count,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = PATH_TO_CREATE_POST
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    groups = Group.objects.all()
    template = PATH_TO_CREATE_POST
    required_post = Post.objects.get(pk=post_id)
    is_edit: bool = True
    if required_post.author == request.user:
        form = PostForm(request.POST or None, instance=required_post)
        if form.is_valid():
            form.save()
            return redirect('posts:profile', username=request.user.username)
        context = {
            'form': form,
            'groups': groups,
            'is_edit': is_edit,
        }
        return render(request, template, context)
    else:
        return redirect('posts:post_detail', post_id=post_id)

yatube/templates/includes/footer.html
{% comment %}
  Использованы классы бустрапа:
  border-top: создаёт тонкую линию сверху блока
  text-center: выравнивает текстовые блоки внутри блока по центру
  py-3: контент внутри размещается с отступом сверху и снизу
  тег span используется для добавления нужных стилей отдельным участкам текста
  {{ year }} {% now "Y" %} not working? 
{% endcomment %}       
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
            href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}" 
            href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/post_view.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <p>{{ post.text }}</p>
</article>